### ISSUE TITLE
Wrong directory with openVPN 2.4.0

### ISSUE THREAD

**Issue by kuroneko007** [xmikos/qopenvpn#1]
As referenced [here](https://www.archlinux.org/news/openvpn-240-update-requires-administrative-interaction/), openVPN 2.4.0 release changes the name of the systemd client service, and also the location of .conf files. This breaks current qopenvpn functionality as the hardcoded .conf directory is wrong (/etc/openvpn instead of /etc/openvpn/client)

**Comment by olm52** [comment]
Waiting for the fix I have changed 
cmdline.extend(["systemctl", command, "openvpn@{}".format(settings.value("vpn_name"))])
to
cmdline.extend(["systemctl", command, "openvpn-server@{}".format(settings.value("vpn_name"))])
and
 for f in sorted(glob.glob("/etc/openvpn/*.conf")):
to
 for f in sorted(glob.glob("/etc/openvpn/server/*.conf")):

in /usr/lib/python3.6/site-packages/qopenvpn/__main__.py

**Comment by kuroneko007** [comment]
In both cases where you have added 'server' should be 'client'.
I've done the same fix locally.
