### ISSUE TITLE
Compatible with systemd-networkd? 

### ISSUE THREAD

**Issue by rainbowgoblin** [xmikos/qopenvpn#6]
I'm running Arch Linux, where they recommend systemd-networkd as an alternative to network manager. I have two VPN configurations set up in /etc/openvpn/client/ and starting/stopping works on the command line, but Qopenvpn doesn't detect them.

**Comment by hcisnerosg** [comment]
> I'm running Arch Linux, where they recommend systemd-networkd as an alternative to network manager. I have two VPN configurations set up in /etc/openvpn/client/ and starting/stopping works on the command line, but Qopenvpn doesn't detect them.

Make sure to rename (or at least duplicate) your xxxx.ovpn client configuration file as xxxx.conf

**Comment by rainbowgoblin** [comment]
That's not the problem, they both have the .conf extension.

**Comment by rainbowgoblin** [comment]
Ah! I figured it out: the default permissions on /etc/openvpn/client were 700. Changed to 755 and Qopenvpn now sees my VPNs.
